<a href="https://colab.research.google.com/github/gitguy007/2026-ColabWorks/blob/main/20261001_ColabWorks!_Build_a_Multimodal_Retrieval_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
RAG-Anything Tutorial: Build a Multimodal Retrieval Pipeline for Text, Tables, Equations, and Images in Colab

URL : https://www.marktechpost.com/2026/07/02/rag-anything-tutorial-build-a-multimodal-retrieval-pipeline-for-text-tables-equations-and-images-in-colab/

In [ ]:
import os
import re
import sys
import json
import time
import shutil
import hashlib
import asyncio
import inspect
import getpass
import subprocess
import importlib
import importlib.metadata
from pathlib import Path
from typing import List, Dict, Any
def run_shell(cmd, check=True):
   print(f"\n$ {cmd}")
   result = subprocess.run(cmd, shell=True, text=True)
   if check and result.returncode != 0:
       raise RuntimeError(f"Command failed: {cmd}")
   return result.returncode
print("=" * 80)
print("RAG-Anything Advanced Colab Tutorial")
print("=" * 80)
print("\n[1/10] Installing dependencies...")
for module_name in list(sys.modules):
   if module_name == "PIL" or module_name.startswith("PIL."):
       del sys.modules[module_name]
run_shell(
   'pip -q install -U '
   '"raganything[image,text]" '
   '"openai>=1.0.0" '
   '"python-dotenv" '
   '"reportlab" '
   '"pandas" '
   '"matplotlib" '
   '"tabulate"'
)
run_shell('pip -q install --no-cache-dir --force-reinstall "pillow==11.3.0"')
for module_name in list(sys.modules):
   if module_name == "PIL" or module_name.startswith("PIL."):
       del sys.modules[module_name]
importlib.invalidate_caches()
try:
   print("Pillow version:", importlib.metadata.version("Pillow"))
except Exception as e:
   print("Could not read Pillow version:", repr(e))
print("\n[2/10] Importing libraries...")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from openai import AsyncOpenAI
from raganything import RAGAnything, RAGAnythingConfig
from lightrag.utils import EmbeddingFunc
print("Imports successful.")

================================================================================
RAG-Anything Advanced Colab Tutorial
================================================================================

[1/10] Installing dependencies...

$ pip -q install -U "raganything[image,text]" "openai>=1.0.0" "python-dotenv" "reportlab" "pandas" "matplotlib" "tabulate"

$ pip -q install --no-cache-dir --force-reinstall "pillow==11.3.0"
Pillow version: 11.3.0

[2/10] Importing libraries...
Imports successful.

In [ ]:
print("\n[3/10] Preparing directories and runtime settings...")
BASE_DIR = Path("/content/raganything_advanced_tutorial") if Path("/content").exists() else Path.cwd() / "raganything_advanced_tutorial"
ASSET_DIR = BASE_DIR / "assets"
OUTPUT_DIR = BASE_DIR / "output"
WORKING_DIR = BASE_DIR / "rag_storage"
LOG_DIR = BASE_DIR / "logs"
RESET_STORAGE = True
RUN_FULL_DOCUMENT_PARSE = False
PARSER_FOR_FULL_PARSE = "mineru"
PARSE_METHOD = "auto"
for d in [BASE_DIR, ASSET_DIR, OUTPUT_DIR, WORKING_DIR, LOG_DIR]:
   d.mkdir(parents=True, exist_ok=True)
if RESET_STORAGE and WORKING_DIR.exists():
   shutil.rmtree(WORKING_DIR)
   WORKING_DIR.mkdir(parents=True, exist_ok=True)
os.environ["LOG_DIR"] = str(LOG_DIR)
os.environ["SUMMARY_LANGUAGE"] = "English"
os.environ["ENABLE_LLM_CACHE"] = "false"
os.environ["ENABLE_LLM_CACHE_FOR_EXTRACT"] = "false"
os.environ["MAX_ASYNC"] = "2"
os.environ["CHUNK_SIZE"] = "900"
os.environ["CHUNK_OVERLAP_SIZE"] = "120"
os.environ["TIMEOUT"] = "240"
for var in [
   "OPENAI_API_KEY",
   "OPENAI_ORG_ID",
   "OPENAI_ORGANIZATION",
   "OPENAI_PROJECT",
   "OPENAI_DEFAULT_HEADERS",
   "LLM_BINDING_API_KEY",
   "LLM_BINDING_HOST",
]:
   os.environ.pop(var, None)
print(f"Base directory: {BASE_DIR}")
print(f"Assets directory: {ASSET_DIR}")
print(f"Storage directory: {WORKING_DIR}")
print("\n[4/10] Entering OpenAI API key securely...")
def clean_api_key(raw_value: str) -> str:
   raw_value = str(raw_value or "").strip()
   raw_value = raw_value.replace("Bearer ", "").replace("bearer ", "").strip()
   raw_value = raw_value.strip("'").strip('"').strip("`").strip()
   if "=" in raw_value:
       raw_value = raw_value.split("=", 1)[1].strip().strip("'").strip('"').strip("`")
   raw_value = re.sub(r"\s+", "", raw_value)
   raw_value = raw_value.encode("ascii", errors="ignore").decode("ascii").strip()
   return raw_value
OPENAI_API_KEY_RAW = getpass.getpass("Paste your OpenAI API key here. Input is hidden: ")
OPENAI_API_KEY = clean_api_key(OPENAI_API_KEY_RAW)
if not OPENAI_API_KEY:
   raise ValueError(
       "No API key was captured. Paste the key into the hidden input box and press Enter."
   )
print("Captured key length:", len(OPENAI_API_KEY))
print("Captured key prefix:", OPENAI_API_KEY[:12] + "...")
print("Captured key suffix:", "..." + OPENAI_API_KEY[-6:])
LLM_MODEL = "gpt-4o-mini"
VISION_MODEL = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 1536
openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)
os.environ["LLM_MODEL"] = LLM_MODEL
os.environ["VISION_MODEL"] = VISION_MODEL
os.environ["EMBEDDING_MODEL"] = EMBEDDING_MODEL
os.environ["EMBEDDING_DIM"] = str(EMBEDDING_DIM)
print("Testing OpenAI chat API with the captured key...")
try:
   test_response = await openai_client.chat.completions.create(
       model=LLM_MODEL,
       messages=[{"role": "user", "content": "Reply with exactly: ok"}],
       temperature=0,
   )
   print("Chat API test response:", test_response.choices[0].message.content)
except Exception as e:
   raise RuntimeError(
       "The key was captured, but OpenAI rejected the request or the account/model access failed. "
       "Check billing, project permissions, and make sure this is an OpenAI Platform API key."
   ) from e
print("\nTesting OpenAI embedding API...")
try:
   test_embedding = await openai_client.embeddings.create(
       model=EMBEDDING_MODEL,
       input=["RAG-Anything embedding test"],
   )
   print("Embedding vector length:", len(test_embedding.data[0].embedding))
except Exception as e:
   raise RuntimeError(
       "Chat worked, but embeddings failed. Make sure your API key has permission for embeddings."
   ) from e
print("OpenAI API key is working.")
print(f"Chat model: {LLM_MODEL}")
print(f"Vision model: {VISION_MODEL}")
print(f"Embedding model: {EMBEDDING_MODEL}")
print(f"Embedding dimension: {EMBEDDING_DIM}")

[3/10] Preparing directories and runtime settings...
Base directory: /content/raganything_advanced_tutorial
Assets directory: /content/raganything_advanced_tutorial/assets
Storage directory: /content/raganything_advanced_tutorial/rag_storage

[4/10] Entering OpenAI API key securely...
Paste your OpenAI API key here. Input is hidden: ··········
Captured key length: 167
Captured key prefix: sk-svcacct-v...
Captured key suffix: ...fvsgAA
Testing OpenAI chat API with the captured key...
Chat API test response: ok

Testing OpenAI embedding API...
Embedding vector length: 1536
OpenAI API key is working.
Chat model: gpt-4o-mini
Vision model: gpt-4o-mini
Embedding model: text-embedding-3-small
Embedding dimension: 1536

In [ ]:
print("\n[5/10] Creating a synthetic multimodal report...")
monthly_data = pd.DataFrame(
   {
       "Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
       "Query Volume": [1200, 1700, 2100, 2600, 3300, 4100],
       "Hybrid Accuracy": [0.71, 0.74, 0.79, 0.83, 0.87, 0.91],
       "Average Latency ms": [980, 920, 850, 790, 760, 730],
   }
)
table_md = monthly_data.to_markdown(index=False)
plt.figure(figsize=(8, 4.8))
plt.plot(monthly_data["Month"], monthly_data["Query Volume"], marker="o", label="Query Volume")
plt.plot(monthly_data["Month"], monthly_data["Hybrid Accuracy"] * 4000, marker="s", label="Hybrid Accuracy scaled")
plt.title("Multimodal RAG Usage and Quality Trend")
plt.xlabel("Month")
plt.ylabel("Volume / Scaled Accuracy")
plt.legend()
plt.grid(True, alpha=0.3)
plt.text(
   0.02,
   0.95,
   "Synthetic figure: usage rises while latency falls",
   transform=plt.gca().transAxes,
   fontsize=9,
   verticalalignment="top",
   bbox=dict(boxstyle="round", alpha=0.15),
)
chart_path = ASSET_DIR / "raganything_quality_trend.png"
plt.tight_layout()
plt.savefig(chart_path, dpi=180)
plt.close()
report_pdf_path = ASSET_DIR / "synthetic_multimodal_rag_report.pdf"
c = canvas.Canvas(str(report_pdf_path), pagesize=letter)
width, height = letter
c.setFont("Helvetica-Bold", 18)
c.drawString(0.8 * inch, height - 0.8 * inch, "Synthetic Multimodal RAG Evaluation Report")
c.setFont("Helvetica", 10)
intro_lines = [
   "This report evaluates a synthetic multimodal RAG pipeline for enterprise documents.",
   "The knowledge base includes text, tables, equations, and visual evidence.",
   "The central hypothesis is that hybrid retrieval improves answer quality when evidence spans modalities.",
]
y = height - 1.25 * inch
for line in intro_lines:
   c.drawString(0.8 * inch, y, line)
   y -= 0.22 * inch
c.setFont("Helvetica-Bold", 12)
c.drawString(0.8 * inch, y - 0.1 * inch, "Table 1. Monthly system measurements")
y -= 0.4 * inch
c.setFont("Courier", 7.5)
for row in table_md.splitlines():
   c.drawString(0.8 * inch, y, row[:120])
   y -= 0.17 * inch
c.setFont("Helvetica-Bold", 12)
c.drawString(0.8 * inch, y - 0.15 * inch, "Equation 1. Weighted multimodal score")
y -= 0.45 * inch
c.setFont("Helvetica", 9)
c.drawString(
   0.8 * inch,
   y,
   "Score(q, d) = alpha * Sim_text(q, d) + beta * Sim_graph(q, d) + gamma * Sim_visual(q, d)",
)
y -= 0.5 * inch
c.drawImage(str(chart_path), 0.8 * inch, y - 2.8 * inch, width=6.5 * inch, height=2.6 * inch)
c.showPage()
c.setFont("Helvetica-Bold", 16)
c.drawString(0.8 * inch, height - 0.8 * inch, "Interpretation and Findings")
c.setFont("Helvetica", 10)
findings = [
   "Hybrid retrieval combines semantic similarity with graph-based relationship navigation.",
   "The synthetic table shows accuracy improving from 0.71 to 0.91 over six months.",
   "The generated figure shows query volume increasing while latency gradually decreases.",
   "Equation-level retrieval is useful when the question depends on scoring logic rather than plain prose.",
   "A multimodal system should preserve page index, captions, footnotes, and local image paths for traceability.",
]
y = height - 1.25 * inch
for finding in findings:
   c.drawString(0.8 * inch, y, "- " + finding)
   y -= 0.28 * inch
c.save()
print(f"Created chart: {chart_path}")
print(f"Created PDF: {report_pdf_path}")
print("\nSynthetic table:")
display(monthly_data)

[5/10] Creating a synthetic multimodal report...
Created chart: /content/raganything_advanced_tutorial/assets/raganything_quality_trend.png
Created PDF: /content/raganything_advanced_tutorial/assets/synthetic_multimodal_rag_report.pdf

Synthetic table:

  Month  Query Volume  Hybrid Accuracy  Average Latency ms
0   Jan          1200             0.71                 980
1   Feb          1700             0.74                 920
2   Mar          2100             0.79                 850
3   Apr          2600             0.83                 790
4   May          3300             0.87                 760
5   Jun          4100             0.91                 730

In [ ]:
print("\n[6/10] Building direct multimodal content_list...")
content_list: List[Dict[str, Any]] = [
   {
       "type": "text",
       "text": (
           "This synthetic report evaluates a multimodal retrieval augmented generation system. "
           "The system indexes textual explanations, a structured performance table, a scoring equation, "
           "and a trend figure. The main goal is to answer questions whose evidence is distributed across "
           "several document modalities rather than one plain text passage."
       ),
       "page_idx": 0,
   },
   {
       "type": "table",
       "table_body": table_md,
       "table_caption": ["Table 1: Monthly query volume, hybrid accuracy, and average latency."],
       "table_footnote": ["Synthetic measurements created for a Colab tutorial."],
       "page_idx": 0,
   },
   {
       "type": "equation",
       "latex": r"Score(q,d)=\alpha \cdot Sim_{text}(q,d)+\beta \cdot Sim_{graph}(q,d)+\gamma \cdot Sim_{visual}(q,d)",
       "text": (
           "Weighted multimodal retrieval score. Alpha controls text similarity, beta controls graph relationship "
           "similarity, and gamma controls visual similarity."
       ),
       "page_idx": 0,
   },
   {
       "type": "image",
       "img_path": str(chart_path.resolve()),
       "image_caption": ["Figure 1: Multimodal RAG usage and quality trend."],
       "image_footnote": ["The line chart is synthetic and generated inside this tutorial."],
       "page_idx": 0,
   },
   {
       "type": "text",
       "text": (
           "The key finding is that hybrid retrieval is preferred for cross-modal questions. "
           "Local retrieval is useful for entity-specific lookup, global retrieval is useful for broader themes, "
           "and naive retrieval is a simpler baseline. In this report, hybrid accuracy rises from 0.71 in January "
           "to 0.91 in June, while average latency drops from 980 milliseconds to 730 milliseconds."
       ),
       "page_idx": 1,
   },
]
content_list_path = ASSET_DIR / "content_list.json"
with open(content_list_path, "w", encoding="utf-8") as f:
   json.dump(content_list, f, indent=2, ensure_ascii=False)
print(f"Saved content list: {content_list_path}")

[6/10] Building direct multimodal content_list...
Saved content list: /content/raganything_advanced_tutorial/assets/content_list.json

In [ ]:
print("\n[7/10] Defining clean OpenAI model and embedding functions...")
async def llm_model_func(prompt, system_prompt=None, history_messages=None, **kwargs):
   messages = []
   if system_prompt:
       messages.append({"role": "system", "content": str(system_prompt)})
   for msg in history_messages or []:
       if isinstance(msg, dict) and "role" in msg and "content" in msg:
           messages.append(msg)
   messages.append({"role": "user", "content": str(prompt)})
   allowed_kwargs = {}
   for key in ["temperature", "top_p", "max_tokens", "response_format"]:
       if key in kwargs and kwargs[key] is not None:
           allowed_kwargs[key] = kwargs[key]
   response = await openai_client.chat.completions.create(
       model=LLM_MODEL,
       messages=messages,
       **allowed_kwargs,
   )
   return response.choices[0].message.content or ""
async def vision_model_func(
   prompt,
   system_prompt=None,
   history_messages=None,
   image_data=None,
   messages=None,
   **kwargs,
):
   allowed_kwargs = {}
   for key in ["temperature", "top_p", "max_tokens", "response_format"]:
       if key in kwargs and kwargs[key] is not None:
           allowed_kwargs[key] = kwargs[key]
   if messages:
       clean_messages = [m for m in messages if m is not None]
       response = await openai_client.chat.completions.create(
           model=VISION_MODEL,
           messages=clean_messages,
           **allowed_kwargs,
       )
       return response.choices[0].message.content or ""
   built_messages = []
   if system_prompt:
       built_messages.append({"role": "system", "content": str(system_prompt)})
   for msg in history_messages or []:
       if isinstance(msg, dict) and "role" in msg and "content" in msg:
           built_messages.append(msg)
   if image_data:
       built_messages.append(
           {
               "role": "user",
               "content": [
                   {"type": "text", "text": str(prompt)},
                   {
                       "type": "image_url",
                       "image_url": {"url": f"data:image/jpeg;base64,{image_data}"},
                   },
               ],
           }
       )
   else:
       built_messages.append({"role": "user", "content": str(prompt)})
   response = await openai_client.chat.completions.create(
       model=VISION_MODEL,
       messages=built_messages,
       **allowed_kwargs,
   )
   return response.choices[0].message.content or ""
async def openai_embedding_func(texts, **kwargs):
   if isinstance(texts, str):
       texts = [texts]
   texts = [str(t) for t in texts]
   response = await openai_client.embeddings.create(
       model=EMBEDDING_MODEL,
       input=texts,
   )
   vectors = [item.embedding for item in response.data]
   return np.array(vectors, dtype=np.float32)
embedding_func = EmbeddingFunc(
   embedding_dim=EMBEDDING_DIM,
   max_token_size=8192,
   func=openai_embedding_func,
)
print("Model and embedding functions ready.")

[7/10] Defining clean OpenAI model and embedding functions...
Model and embedding functions ready.

In [ ]:
print("\n[8/10] Initializing RAG-Anything...")
config = RAGAnythingConfig(
   working_dir=str(WORKING_DIR),
   parser=PARSER_FOR_FULL_PARSE,
   parse_method=PARSE_METHOD,
   enable_image_processing=True,
   enable_table_processing=True,
   enable_equation_processing=True,
)
rag = RAGAnything(
   config=config,
   llm_model_func=llm_model_func,
   vision_model_func=vision_model_func,
   embedding_func=embedding_func,
)
async def maybe_await(value):
   if inspect.isawaitable(value):
       return await value
   return value
if hasattr(rag, "initialize_storages"):
   try:
       await maybe_await(rag.initialize_storages())
       print("RAG-Anything storages initialized.")
   except Exception as e:
       print("Storage initialization skipped or already handled:", repr(e))
print(f"Working directory: {WORKING_DIR}")
print("\n[9/10] Inserting multimodal content and running retrieval queries...")
async def insert_demo_content():
   await rag.insert_content_list(
       content_list=content_list,
       file_path=str(report_pdf_path.name),
       split_by_character=None,
       split_by_character_only=False,
       doc_id="synthetic-multimodal-rag-report",
       display_stats=True,
   )
await insert_demo_content()
print("Insertion complete.")
queries = [
   "What is the main purpose of the multimodal RAG report?",
   "How did hybrid accuracy and latency change from January to June?",
   "Why is hybrid retrieval better than naive retrieval for this report?",
   "What does the weighted multimodal score equation mean?",
]
async def safe_aquery(question, mode="hybrid", vlm_enhanced=False):
   try:
       return await rag.aquery(question, mode=mode, vlm_enhanced=vlm_enhanced)
   except TypeError:
       return await rag.aquery(question, mode=mode)
async def run_query_suite():
   results = []
   for mode in ["naive", "local", "global", "hybrid"]:
       print("\n" + "=" * 80)
       print(f"QUERY MODE: {mode.upper()}")
       print("=" * 80)
       for q in queries:
           print(f"\nQuestion: {q}")
           try:
               answer = await safe_aquery(q, mode=mode, vlm_enhanced=False)
           except Exception as e:
               answer = f"Query failed in mode={mode}: {repr(e)}"
           print("\nAnswer:")
           print(answer)
           print("-" * 80)
           results.append(
               {
                   "mode": mode,
                   "question": q,
                   "answer_preview": str(answer)[:700],
               }
           )
   return pd.DataFrame(results)
query_results_df = await run_query_suite()
print("\nQuery result preview:")
display(query_results_df)

INFO: RAGAnything initialized with config:
INFO:   Working directory: /content/raganything_advanced_tutorial/rag_storage
INFO:   Parser: mineru
INFO:   Parse method: auto
INFO:   Multimodal processing - Image: True, Table: True, Equation: True
INFO:   Max concurrent files: 1

[8/10] Initializing RAG-Anything...
Working directory: /content/raganything_advanced_tutorial/rag_storage

[9/10] Inserting multimodal content and running retrieval queries...

INFO: Parser 'mineru' installation verified
INFO: Initializing LightRAG with parameters: {'working_dir': '/content/raganything_advanced_tutorial/rag_storage'}
INFO: [] Created new empty graph file: /content/raganything_advanced_tutorial/rag_storage/graph_chunk_entity_relation.graphml
INFO: [] Process 617 KV load full_docs with 0 records
INFO: [] Process 617 KV load text_chunks with 0 records
INFO: [] Process 617 KV load full_entities with 0 records
INFO: [] Process 617 KV load full_relations with 0 records
INFO: [] Process 617 KV load entity_chunks with 0 records
INFO: [] Process 617 KV load relation_chunks with 0 records
INFO: [] Process 617 KV load llm_response_cache with 0 records
INFO: [] Process 617 doc status load doc_status with 0 records
INFO: [] Process 617 KV load parse_cache with 0 records
INFO: [] Process 617 KV load multimodal_status with 0 records
INFO: Multimodal processors initialized with context support
INFO: Available processors: ['image', 'table', 'equation', 'generic']
INFO: Context configuration: ContextConfig(context_window=1, context_mode='page', max_context_tokens=2000, include_headers=True, include_captions=True, filter_content_types=['text'])
INFO: LightRAG, parse cache, multimodal status cache, and multimodal processors initialized
INFO: Starting direct content list insertion for: synthetic_multimodal_rag_report.pdf (5 items)
INFO:
Content Information:
INFO: * Total blocks in content_list: 5
INFO: * Content block types:
INFO:   - text: 2
INFO:   - table: 1
INFO:   - equation: 1
INFO:   - image: 1
INFO: Content separation complete:
INFO:   - Text content length: 707 characters
INFO:   - Multimodal items count: 3
INFO:   - Multimodal type distribution: {'table': 1, 'equation': 1, 'image': 1}
INFO: Setting content source for context-aware multimodal processing...
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set with format: minerU
INFO: Content source set for context extraction (format: minerU)
INFO: Starting text content insertion into LightRAG...
INFO: Processing 1 document(s)
INFO: Extracting stage 1/1: synthetic_multimodal_rag_report.pdf
INFO: Processing d-id: synthetic-multimodal-rag-report
INFO: Embedding func: 8 new workers initialized (Timeouts: Func: 30s, Worker: 60s, Health Check: 75s)
INFO: LLM func: 4 new workers initialized (Timeouts: Func: 180s, Worker: 360s, Health Check: 375s)
INFO:  == LLM cache == saving: default:extract:6fe72615e2c14c26865fec630d8624fc
INFO:  == LLM cache == saving: default:extract:65d37720f2530c1646e8600874c582da
INFO: Chunk 1 of 1 extracted 11 Ent + 6 Rel chunk-a3c68fec2c59ca6e680e9ee0acf4945f
INFO: Merging stage 1/1: synthetic_multimodal_rag_report.pdf
INFO: Phase 1: Processing 11 entities from synthetic-multimodal-rag-report (async: 8)
INFO: Phase 2: Processing 6 relations from synthetic-multimodal-rag-report (async: 8)
INFO: Phase 3: Updating final 11(11+0) entities and  6 relations from synthetic-multimodal-rag-report
INFO: Completed merging: 11 entities, 0 extra entities, 6 relations
INFO: [] Writing graph with 11 nodes, 6 edges
INFO: In memory DB persist to disk
INFO: Completed processing file 1/1: synthetic_multimodal_rag_report.pdf
INFO: Enqueued document processing pipeline stopped
INFO: Text content insertion complete
INFO: Starting multimodal content processing...
INFO: Starting to process 3 multimodal content items
INFO: Multimodal chunk generation progress: 1/3 (33.3%)
INFO: Multimodal chunk generation progress: 2/3 (66.7%)
INFO: Multimodal chunk generation progress: 3/3 (100.0%)
INFO: Generated descriptions for 3/3 multimodal items using correct processors
INFO:  == LLM cache == saving: default:extract:3cfbfa9fcb67b0cce8a3a4db5d9cf371
INFO:  == LLM cache == saving: default:extract:5f5c22ec874ba697f1dc466db50d7202
INFO:  == LLM cache == saving: default:extract:1823f1dddd9ad98445d3e41f0c70d847
INFO:  == LLM cache == saving: default:extract:6fb2b61b6fbff38047a56b7330f069c2
INFO: Chunk 1 of 3 extracted 8 Ent + 7 Rel chunk-268fcd0f57621736b1facf99f10027b8
INFO:  == LLM cache == saving: default:extract:b73faf61b55e7435f413d0f9720b163b
INFO: Chunk 2 of 3 extracted 13 Ent + 6 Rel chunk-426a869b8919ecaa0c7df8d2c84796aa
INFO:  == LLM cache == saving: default:extract:24d8149e57eec1434df1b956a86d7a0c
INFO: Chunk 3 of 3 extracted 14 Ent + 10 Rel chunk-de919e0cb077ed7866b247fa5c859b2c
INFO: Extracted entities from 3 multimodal chunks
INFO: Added 35 belongs_to relations for multimodal entities
INFO: Merging stage 1/1: synthetic_multimodal_rag_report.pdf
INFO: Phase 1: Processing 31 entities from synthetic-multimodal-rag-report (async: 8)
INFO: Merged: `Hybrid Accuracy` | 1+2
INFO: Merged: `Average Latency` | 1+2
INFO: Merged: `Multimodal Retrieval Augmented Generation System` | 1+1
INFO: Merged: `Hybrid Retrieval` | 1+1
INFO: Merged: `Local Retrieval` | 1+1
INFO: Merged: `Global Retrieval` | 1+1
INFO: Merged: `Naive Retrieval` | 1+1
INFO: Merged: `Synthetic Report` | 1+1
INFO: Phase 2: Processing 58 relations from synthetic-multimodal-rag-report (async: 8)
INFO: Merged: `Hybrid Retrieval`~`Multimodal Retrieval Augmented Generation System` | 1+1
INFO: Merged: `Local Retrieval`~`Multimodal Retrieval Augmented Generation System` | 1+1
INFO: Merged: `Global Retrieval`~`Multimodal Retrieval Augmented Generation System` | 1+1
INFO: Merged: `Multimodal Retrieval Augmented Generation System`~`Synthetic Report` | 1+1
INFO: Phase 3: Updating final 31(31+0) entities and  58 relations from synthetic-multimodal-rag-report
INFO: Completed merging: 31 entities, 0 extra entities, 58 relations
INFO: [] Writing graph with 37 nodes, 60 edges
INFO: In memory DB persist to disk
INFO: Updated doc_status: added 3 multimodal chunks to standard chunks_list (total chunks: 4)
INFO: Multimodal content processing complete
INFO: Content list insertion complete for: synthetic_multimodal_rag_report.pdf
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: naive

Insertion complete.

================================================================================
QUERY MODE: NAIVE
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO: Naive query: 4 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 4 chunks
INFO:  == LLM cache == saving: naive:query:ef132e71b95f9af667fe42da122a003a
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: naive

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system that is designed to answer questions where the evidence is distributed across various document modalities, rather than confined to a single plain text passage. The report highlights the effectiveness of using hybrid retrieval methods for cross-modal questions, suggesting that it is preferable to approach queries that require information from diverse sources such as text, graphs, and visual content.

Additionally, the report provides an analysis of performance metrics, showing improvements in hybrid accuracy and reductions in latency over a specific period, which further underscores the system's efficacy and its importance in enhancing user interactions within AI systems that necessitate cross-modal understanding and retrieval.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO: Naive query: 4 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 4 chunks
INFO:  == LLM cache == saving: naive:query:23e96322a492bd2718c5044d66d3998f
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: naive
INFO: Naive query: 4 chunks (chunk_top_k:20 cosine:0.2)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 4 chunks

Answer:
From January to June, the hybrid accuracy and average latency displayed notable changes:

- **Hybrid Accuracy**:
  - **January**: 0.71
  - **June**: 0.91
  - This indicates a steady increase in hybrid accuracy, reflecting improvements in the system's performance over this period.

- **Average Latency**:
  - **January**: 980 ms
  - **June**: 730 ms
  - There was a decrease in average latency, suggesting that the efficiency of the retrieval system improved as the months progressed.

Overall, the data shows a positive trend, with hybrid accuracy rising and average latency decreasing, illustrating the effectiveness of the multimodal retrieval augmented generation system during this timeframe.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: naive:query:872ded3f24918d2560030726e8f8881d
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: naive
INFO: Naive query: 4 chunks (chunk_top_k:20 cosine:0.2)

Answer:
Hybrid retrieval is deemed superior to naive retrieval in the context of the report due to several key findings:

1. **Performance on Cross-Modal Questions**: The main advantage of hybrid retrieval is its effectiveness in answering questions whose evidence is distributed across various document modalities rather than just relying on a single text passage. This is essential in multimodal retrieval where different types of data (text, images, etc.) are involved.

2. **Accuracy Improvement**: The report shows a significant improvement in hybrid accuracy, which rose from 0.71 in January to 0.91 in June. In contrast, naive retrieval does not have the same capacity to integrate disparate information, which limits its accuracy and effectiveness.

3. **Efficiency Gain**: Alongside increased accuracy, there was a notable decline in average latency from 980 milliseconds to 730 milliseconds over the evaluated period for hybrid retrieval. This indicates that not only is hybrid retrieval more accurate, but it is also more efficient, allowing for faster query responses compared to naive retrieval.

4. **Contextual Relevance**: Hybrid retrieval utilizes a combination of local and global retrieval techniques. Local retrieval helps in finding specific entities, whereas global retrieval caters to broader themes, enhancing the overall contextual relevance of the information retrieved. Naive retrieval lacks this sophisticated methodology and thus may miss crucial connections in the data.

These characteristics underline why hybrid retrieval is preferred in scenarios involving complex, cross-modal questions, as highlighted in the findings of the report.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 4 chunks
INFO:  == LLM cache == saving: naive:query:bcf82c4b1d9feab83f713f92b98c025b
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: local

Answer:
The **weighted multimodal retrieval score equation** is a mathematical framework used to assess the effectiveness of retrieval systems that integrate various data types, such as text, graphs, and visual content.

### Key Components of the Equation

1. **Variables**:
   - **Alpha (α)**: Represents the weight assigned to text similarity.
   - **Beta (β)**: Represents the weight assigned to graph relationship similarity.
   - **Gamma (γ)**: Represents the weight assigned to visual similarity.

2. **Structure**:
   The general formula for the weighted multimodal retrieval score can be expressed as:
   \[
   \text{Score} = α \times \text{TextSimilarity} + β \times \text{GraphSimilarity} + γ \times \text{VisualSimilarity}
   \]
   This formula indicates that the total score is a weighted sum of the similarities derived from each modality.

### Purpose and Applications

- **Effectiveness in Information Retrieval**: The equation helps in quantifying how well a retrieval system can pull relevant content that corresponds to a user's query by appropriately weighting different types of data based on their relevance.

- **Adaptability**: It shows how systems can prioritize various modalities according to contextual needs, which is particularly useful in hybrid models that leverage multiple information sources for improved performance.

- **Real-World Use**: This framework aids in designing more efficient search engines and recommendation systems that utilize multimodal data to offer a thorough understanding of the information landscape.

Overall, the weighted multimodal retrieval score equation is significant for developing AI systems that require a cross-modal understanding and retrieval capability.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: LOCAL
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: local:keywords:a4068fef811d9b366a986d72a9464aa6
INFO: Query nodes: Report analysis, Data integration, Document retrieval, Applications (top_k:40, cosine:0.2)
INFO: Local query: 29 entites, 60 relations
INFO: Raw search results: 29 entities, 60 relations, 0 vector chunks
INFO: After truncation: 29 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 29 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E13/1 E11/2 E4/3 E13/4
INFO:  == LLM cache == saving: local:query:aa2de01f02c6fbfd372ccea8cda62fca
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: local

Answer:
The main purpose of the multimodal RAG (Retrieval Augmented Generation) report is to evaluate a multimodal retrieval augmented generation system. This system is designed to index various document modalities to effectively answer questions where the evidence is distributed across multiple types of information, rather than being contained in a single plain text passage.

The report highlights key findings, such as the preference for hybrid retrieval methods when addressing cross-modal questions, and discusses different retrieval strategies including local retrieval for entity-specific lookups, global retrieval for broader thematic exploration, and naive retrieval as a simpler baseline for comparison. It also presents performance metrics illustrating improvements in hybrid accuracy and reductions in average latency over the evaluation period from January to June.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: local:keywords:6dac9da7fc516ac3bb6d10c7b6892a96
INFO: Query nodes: January, June, Performance metrics, Data comparison (top_k:40, cosine:0.2)
INFO: Local query: 29 entites, 56 relations
INFO: Raw search results: 29 entities, 56 relations, 0 vector chunks
INFO: After truncation: 29 entities, 56 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 29 entities, 56 relations, 4 chunks
INFO: Final chunks S+F/O: E14/1 E10/2 E6/3 E6/4
INFO:  == LLM cache == saving: local:query:df3b7af71ffb0f555d78489e441c727c
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: local

Answer:
From January to June, the **Hybrid Accuracy** and **Average Latency** of the multimodal retrieval system exhibited significant changes:

- **Hybrid Accuracy**:
  - Increased from **0.71 in January** to **0.91 in June**. This rise indicates improved effectiveness in the hybrid retrieval method over this period.

- **Average Latency**:
  - Decreased from **980 milliseconds in January** to **730 milliseconds in June**. This reduction in latency signals an enhancement in the system's efficiency and response time.

These changes reflect a positive correlation between the increase in hybrid accuracy and the decrease in average latency, showcasing the system's overall improvement during the six-month span.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: local:keywords:d9d14f2b12519ab37c089021b26076c7
INFO: Query nodes: Information retrieval, Performance comparison, Effectiveness, Efficiency (top_k:40, cosine:0.2)
INFO: Local query: 32 entites, 60 relations
INFO: Raw search results: 32 entities, 60 relations, 0 vector chunks
INFO: After truncation: 32 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 32 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E11/1 E11/2 E13/3 E8/4
INFO:  == LLM cache == saving: local:query:8a3a8a6ae14e1cb8f37194463619cd8f
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: local

Answer:
Hybrid retrieval is preferred over naive retrieval in the context of the report due to several key advantages that enhance its efficacy in answering complex, cross-modal questions.

### Advantages of Hybrid Retrieval
1. **Multi-Modal Integration**: Hybrid retrieval combines multiple retrieval approaches, leveraging different sources of information, which includes text, graphs, and visual content. This integration enables it to handle queries that require diverse types of evidence spread across various modalities. In contrast, naive retrieval typically focuses on a singular approach, which limits its effectiveness in more complex scenarios.

2. **Higher Hybrid Accuracy**: The report indicates a significant increase in hybrid accuracy, which rises from 0.71 in January to 0.91 in June. This improvement showcases hybrid retrieval's enhanced capability to accurately process and respond to queries compared to the baseline established by naive retrieval.

3. **Improved Performance Metrics**: The use of hybrid retrieval has been correlated with positive performance metrics, such as increased query volume and decreased average latency. For instance, the average latency dropped from 980 milliseconds to 730 milliseconds during the same timeframe indicating better efficiency in processing queries.

4. **Comprehensive Answering**: Hybrid retrieval's capability to address questions that span multiple modalities allows it to provide more comprehensive and nuanced answers, which is crucial when dealing with distributed information. Naive retrieval lacks this adaptability and depth, often leading to incomplete responses.

Overall, these features underscore the overall effectiveness and practical advantages of hybrid retrieval, making it the preferred method as concluded in the report.

### References
- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: local:keywords:a2ae21a828d7158d10d1c4a2f659d5af
INFO: Query nodes: Weighted score, Multimodal, Mathematical equation, Parameters (top_k:40, cosine:0.2)
INFO: Local query: 26 entites, 59 relations
INFO: Raw search results: 26 entities, 59 relations, 0 vector chunks
INFO: After truncation: 26 entities, 59 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 26 entities, 59 relations, 4 chunks
INFO: Final chunks S+F/O: E9/1 E8/2 E9/3 E6/4
INFO:  == LLM cache == saving: local:query:ab18ad315937013c34159b148143b7be
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: global

Answer:
The **Weighted Multimodal Retrieval Score** is a mathematical equation designed to evaluate the effectiveness of a retrieval system that integrates multiple types of data modalities, including text, graphs, and visual content. This score is particularly useful in information retrieval systems that utilize hybrid models to enhance their performance.

### Key Components of the Equation

- **Alpha (α)**: This variable represents the weight assigned to text similarity. It allows the system to emphasize the importance of textual content in the retrieval process.

- **Beta (β)**: This variable signifies the weight assigned to graph relationship similarity. It controls how much influence graph-based data has on the overall retrieval score.

- **Gamma (γ)**: This variable indicates the weight allocated to visual similarity. It measures the impact of visual content in determining the effectiveness of the retrieval.

### Structure of the Equation

The general structure of the weighted multimodal retrieval score can be expressed as:

**Score = α * TextSimilarity + β * GraphSimilarity + γ * VisualSimilarity**

This equation operates under the principle that relevant content can be retrieved more effectively by adjusting the weights assigned to each modality based on its relevance to a user's query. The flexibility in weighting allows the score to adapt to varying contexts, focusing on the most pertinent data type for the query at hand.

By quantitatively assessing the contributions of different modalities, this score plays a crucial role in optimizing retrieval systems, thereby improving user interactions in various applications such as search engines and recommendation systems.

### Practical Implications

The implementation of the weighted multimodal retrieval score not only provides a theoretical framework for measuring similarity across diverse formats but also enhances practical outcomes in AI systems that require a cross-modal understanding of data.

### References

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: GLOBAL
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: global:keywords:5d20543bb08d791e0d630e0e1bd6ba84
INFO: Query edges: Multimodal RAG report, Report purpose (top_k:40, cosine:0.2)
INFO: Global query: 30 entites, 40 relations
INFO: Raw search results: 30 entities, 40 relations, 0 vector chunks
INFO: After truncation: 30 entities, 40 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 30 entities, 40 relations, 4 chunks
INFO: Final chunks S+F/O: E15/1 E8/2 E5/3 E14/4
INFO:  == LLM cache == saving: global:query:90564e50f79d6db3ea2103bcd29ca4de
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: global

Answer:
The main purpose of the multimodal RAG (Retrieval Augmented Generation) report is to evaluate a multimodal retrieval augmented generation system. This system is designed to index various document modalities, aiming to answer questions whose evidence is distributed across multiple formats rather than relying on a single text passage. The report emphasizes the performance of different retrieval methods, particularly highlighting that hybrid retrieval is preferred for cross-modal questions, while also providing insights into local and global retrieval techniques, as well as naive retrieval as a simpler baseline.

Key findings of the report include:

- An increase in hybrid accuracy from **0.71** in January to **0.91** in June.
- A decrease in average latency from **980 milliseconds** to **730 milliseconds** during the same period.

This evaluation underscores the effectiveness and efficiency of the multimodal retrieval system in processing diverse types of information.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: global:keywords:f71f16c803cb715be98be032749bfb68
INFO: Query edges: Hybrid accuracy, Latency change, Time period (top_k:40, cosine:0.2)
INFO: Global query: 26 entites, 40 relations
INFO: Raw search results: 26 entities, 40 relations, 0 vector chunks
INFO: After truncation: 26 entities, 40 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 26 entities, 40 relations, 4 chunks
INFO: Final chunks S+F/O: E10/1 E12/2 E8/3 E6/4
INFO:  == LLM cache == saving: global:query:f352d8a879d4ebc3216de99c29ae2ce9
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: global

Answer:
Between January and June, **Hybrid Accuracy** and **Average Latency** exhibited notable changes:

### Hybrid Accuracy
- **Increased from 0.71 in January to 0.91 in June**. This significant rise indicates an improvement in the effectiveness of the hybrid retrieval method used by the multimodal retrieval system. Enhanced accuracy suggests that the system became better at answering questions that span multiple modalities over this period.

### Average Latency
- **Decreased from 980 milliseconds in January to 730 milliseconds in June**. This reduction reflects an improvement in the efficiency of processing retrieval requests, indicating the system's response time improved alongside the increase in accuracy.

These trends are supported by various performance metrics indicating a positive correlation between increased query volume, better hybrid accuracy, and reduced latency throughout the analyzed timeframe.

### Summary
- **Hybrid Accuracy** improved by **0.20** over six months.
- **Average Latency** improved by **250 milliseconds**, suggesting enhanced system responsiveness.

These findings underscore the operational efficiency and effectiveness of the hybrid retrieval system during the evaluation period.

### References
- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: global:keywords:04838690bd58fe1f2b6703a4d0477cca
INFO: Query edges: Hybrid retrieval, Naive retrieval, Report analysis (top_k:40, cosine:0.2)
INFO: Global query: 27 entites, 40 relations
INFO: Raw search results: 27 entities, 40 relations, 0 vector chunks
INFO: After truncation: 27 entities, 40 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 27 entities, 40 relations, 4 chunks
INFO: Final chunks S+F/O: E8/1 E10/2 E12/3 E7/4
INFO:  == LLM cache == saving: global:query:f23ea4d0d1c06f95e4a8ffcbb5384827
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: global

Answer:
Hybrid retrieval is considered superior to naive retrieval within the context of the report due to its ability to effectively handle cross-modal inquiries. Here are the key reasons:

1. **Integration of Modalities**: Hybrid retrieval combines multiple retrieval approaches, allowing it to analyze various document modalities such as text, graphs, and visual content. This integration enhances the system's capacity to answer complex questions that are distributed across different types of information.

2. **Improved Performance Metrics**: The report indicates a significant improvement in hybrid accuracy over time. Hybrid accuracy increased from **0.71** in January to **0.91** in June, demonstrating that hybrid retrieval is not just more versatile, but also more effective in delivering accurate responses compared to the simpler baseline provided by naive retrieval.

3. **Adaptation to User Queries**: Hybrid retrieval is designed to adaptively prioritize content based on the specific requirements of a user's query. This flexibility allows for a more tailored search experience, making it particularly advantageous for nuanced inquiries that may involve multiple types of data.

4. **Efficiency Indicators**: The report also highlights that while hybrid accuracy improves, the average latency of the system decreases—dropping from **980 milliseconds** to **730 milliseconds**. This implies that hybrid retrieval not only enhances the quality of information retrieval but also does so more swiftly than naive retrieval.

Overall, the combination of improved accuracy, efficiency, and adaptability makes hybrid retrieval a preferred choice for answering questions across multiple modalities, addressing the limitations that naive retrieval does not overcome.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: global:keywords:47c0d33a1277708d05f8234a9775ffcc
INFO: Query edges: Weighted multimodal score, Equation meaning, Score interpretation (top_k:40, cosine:0.2)
INFO: Global query: 29 entites, 40 relations
INFO: Raw search results: 29 entities, 40 relations, 0 vector chunks
INFO: After truncation: 29 entities, 40 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 29 entities, 40 relations, 4 chunks
INFO: Final chunks S+F/O: E9/1 E8/2 E13/3 E9/4
INFO:  == LLM cache == saving: global:query:70c761a4eec45b9a9f520097bc646af0
INFO: Text query completed
INFO: Executing text query: What is the main purpose of the multimodal RAG report?...
INFO: Query mode: hybrid

Answer:
The **weighted multimodal retrieval score** is a mathematical equation that quantifies the effectiveness of a retrieval system integrating multiple data modalities, such as text, graphs, and visual content. This score is particularly useful in information retrieval systems as it allows for a more sophisticated understanding of how relevant content can be retrieved based on the variability across different formats.

### Key Components of the Equation

- **Alpha (α)**: This variable represents the weight assigned to text similarity. It indicates how much influence text content has on the overall score.

- **Beta (β)**: This variable signifies the weight assigned to graph relationship similarity, which measures the significance of graph data in the retrieval process.

- **Gamma (γ)**: Gamma denotes the weight allocated to visual similarity, affecting how visual content is evaluated in the context of the retrieval.

### Functional Structure

The general structure of the equation can be summarized as follows:

**Score = α * TextSimilarity + β * GraphSimilarity + γ * VisualSimilarity**

This equation operates through a linear combination, where each similarity score corresponding to the different modalities is multiplied by its respective weight, emphasizing the ones most relevant to the user's query.

### Application and Significance

The weighted multimodal retrieval score not only embodies a theoretical framework for evaluating similarity but also serves as a practical mechanism for improving user interactions within AI systems that necessitate cross-modal understanding. The approach allows retrieval systems to adaptively prioritize different types of content according to the contextual needs of the query.

This methodological framework resonates with principles from **Linear Algebra** and **Optimization Theory**, further underscoring its mathematical significance and practical utility in enhancing the performance of hybrid retrieval systems.

### Summary

In summary, the weighted multimodal retrieval score equation plays a crucial role in making information retrieval systems more effective by leveraging multiple modalities to derive a comprehensive understanding of user queries and content relevance.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

================================================================================
QUERY MODE: HYBRID
================================================================================

Question: What is the main purpose of the multimodal RAG report?

INFO:  == LLM cache == saving: hybrid:keywords:f80fc2f8a4ba2fff83cb1ac17409b37a
INFO: Query nodes: Data integration, Multimodal analysis, Report objectives (top_k:40, cosine:0.2)
INFO: Local query: 36 entites, 60 relations
INFO: Query edges: Multimodal RAG report, Purpose of reports (top_k:40, cosine:0.2)
INFO: Global query: 31 entites, 40 relations
INFO: Raw search results: 37 entities, 60 relations, 0 vector chunks
INFO: After truncation: 37 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 37 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E15/1 E11/2 E9/3 E14/4
INFO:  == LLM cache == saving: hybrid:query:287e05f6518e7ba197dd2d137838930d
INFO: Text query completed
INFO: Executing text query: How did hybrid accuracy and latency change from January to June?...
INFO: Query mode: hybrid

Answer:
The main purpose of the multimodal Retrieval Augmented Generation (RAG) report is to evaluate a system designed for answering questions using evidence distributed across multiple document modalities. Specifically, the report focuses on the performance of multimodal retrieval systems that integrate various data types, such as text and visual content, to enhance the effectiveness of retrieving relevant information. The report identifies hybrid retrieval as the preferred method for addressing cross-modal questions and also discusses the effectiveness of other retrieval methods like local retrieval, global retrieval, and naive retrieval.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: How did hybrid accuracy and latency change from January to June?

INFO:  == LLM cache == saving: hybrid:keywords:d48983c2f167eb1bac9e74e4fa5431d1
INFO: Query nodes: January, June (top_k:40, cosine:0.2)
INFO: Local query: 14 entites, 39 relations
INFO: Query edges: Hybrid accuracy, Latency, Temporal change (top_k:40, cosine:0.2)
INFO: Global query: 26 entites, 40 relations
INFO: Raw search results: 33 entities, 53 relations, 0 vector chunks
INFO: After truncation: 33 entities, 53 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 33 entities, 53 relations, 4 chunks
INFO: Final chunks S+F/O: E14/1 E15/2 E8/3 E8/4
INFO:  == LLM cache == saving: hybrid:query:d568452911c9871e55d2c8abe27c791a
INFO: Text query completed
INFO: Executing text query: Why is hybrid retrieval better than naive retrieval for this report?...
INFO: Query mode: hybrid

Answer:
Between January and June, significant changes were observed in both **Hybrid Accuracy** and **Average Latency**.

### Hybrid Accuracy
- **Increase**: Hybrid Accuracy rose from **0.71** in January to **0.91** in June. This increase reflects improvements in the effectiveness of the hybrid retrieval method over the analyzed period.

### Average Latency
- **Decrease**: Average Latency improved from **980 milliseconds** in January to **730 milliseconds** in June. This reduction indicates enhanced efficiency in processing retrieval requests as the system evolved.

Overall, the data suggests a positive correlation between the rise in hybrid accuracy and the decrease in average latency, highlighting the effectiveness of the multimodal retrieval system during this timeframe.

### References
- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: Why is hybrid retrieval better than naive retrieval for this report?

INFO:  == LLM cache == saving: hybrid:keywords:d7254aa62dd3ac71fe75b4cf795df7f2
INFO: Query nodes: Report, Efficiency, Accuracy, Document relevance, Data integration (top_k:40, cosine:0.2)
INFO: Local query: 29 entites, 60 relations
INFO: Query edges: Hybrid retrieval, Naive retrieval, Information retrieval improvement (top_k:40, cosine:0.2)
INFO: Global query: 27 entites, 40 relations
INFO: Raw search results: 35 entities, 60 relations, 0 vector chunks
INFO: After truncation: 35 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 35 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E11/1 E13/2 E13/3 E9/4
INFO:  == LLM cache == saving: hybrid:query:6a36d7ae73f775dc13555b8882350127
INFO: Text query completed
INFO: Executing text query: What does the weighted multimodal score equation mean?...
INFO: Query mode: hybrid

Answer:
Hybrid retrieval is considered superior to naive retrieval as outlined in the synthetic report due to its enhanced capability in addressing cross-modal questions involving multiple document modalities. Below are the primary reasons:

### Key Advantages of Hybrid Retrieval

1. **Complexity and Context Understanding**:
   - Hybrid retrieval effectively integrates various sources of information, allowing it to handle complex queries more efficiently. This is particularly significant when the evidence for a query is spread across multiple modalities (e.g., text, graphs, and visual content).

2. **Performance Metrics**:
   - The report demonstrates tangible improvements in hybrid retrieval performance, with hybrid accuracy rising from **0.71 in January to 0.91 in June**. This increase indicates that hybrid retrieval methods are significantly more effective in retrieving relevant information compared to naive retrieval, which does not leverage multi-modality effectively.

3. **Response Time**:
   - The average latency observed in hybrid retrieval decreased from **980 milliseconds to 730 milliseconds**, showcasing that the system became not only more accurate but also faster in processing queries. In contrast, naive retrieval lacks the sophistication for optimizing both response times and accuracy.

4. **Scalability**:
   - Hybrid retrieval is designed to scale with increasing data and query complexity, as evidenced by the growth in query volume from **1200 in January to 4100 in June**. The naive approach is typically a simpler method that may not cope well with the same scale and variety of data.

5. **Flexibility**:
   - Hybrid retrieval methods adaptively weigh different types of content based on their relevance, utilizing specific algorithms like the **weighted multimodal retrieval score**. This adaptability allows the system to prioritize text, graph, or visual data as needed, which naive retrieval does not do.

Overall, these advantages reflect hybrid retrieval's efficacy in navigating the challenges associated with multi-faceted questions, resulting in improved accuracy and efficiency when compared to naive retrieval.

### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Question: What does the weighted multimodal score equation mean?

INFO:  == LLM cache == saving: hybrid:keywords:37424d67852dfc29d5b6fb50ec9dd7fc
INFO: Query nodes: Multimodal score, Weighted score, Mathematical equation (top_k:40, cosine:0.2)
INFO: Local query: 24 entites, 57 relations
INFO: Query edges: Weighted multimodal score, Equation meaning (top_k:40, cosine:0.2)
INFO: Global query: 29 entites, 40 relations
INFO: Raw search results: 32 entities, 57 relations, 0 vector chunks
INFO: After truncation: 32 entities, 57 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 32 entities, 57 relations, 4 chunks
INFO: Final chunks S+F/O: E9/1 E11/2 E13/3 E9/4
INFO:  == LLM cache == saving: hybrid:query:9f9dcb0fb8c1d215dcd54f6e5bbf751c
INFO: Text query completed

Answer:
The **Weighted Multimodal Retrieval Score** is a mathematical equation designed to quantify the effectiveness of a retrieval system that integrates multiple data modalities, such as text, graphs, and visual content.

### Key Components of the Equation

1. **Variables**:
   - **Alpha (α)**: This variable controls the weight assigned to **text similarity** in the equation.
   - **Beta (β)**: This represents the weight assigned to **graph relationship similarity**.
   - **Gamma (γ)**: This indicates the weight allocated to **visual similarity**.

2. **Mathematical Function**:
   The score is typically calculated using a weighted sum or linear combination based on the individual similarity scores derived from the different modalities. The general structure of the equation can be expressed as:
   \[
   \text{Score} = \alpha \times \text{TextSimilarity} + \beta \times \text{GraphSimilarity} + \gamma \times \text{VisualSimilarity}
   \]

This equation plays a critical role in information retrieval systems—especially in hybrid models—because it allows for the adaptive prioritization of different content types based on their relevance to the user's query. By appropriately weighting each modality, the system aims to provide more relevant and comprehensive information, thus improving user interactions.

### Applications

The weighted multimodal retrieval score is utilized in various domains, including search engines and recommendation systems, reflecting its importance in enhancing the retrieval of multimodal data. Its significance is also noted in relation to broader mathematical concepts such as **optimization theory** and **linear algebra**, which help bolster its framework for evaluating similarities across diverse formats.

These insights help in designing more effective systems that can process and understand complex queries requiring information from multiple sources.

### References
### References

- [1] synthetic_multimodal_rag_report.pdf
--------------------------------------------------------------------------------

Query result preview:

,mode,question,answer_preview
0,naive,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
1,naive,How did hybrid accuracy and latency change fro...,"From January to June, the hybrid accuracy and ..."
2,naive,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is deemed superior to naive r...
3,naive,What does the weighted multimodal score equati...,The **weighted multimodal retrieval score equa...
4,local,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal RAG (Retrie...
5,local,How did hybrid accuracy and latency change fro...,"From January to June, the **Hybrid Accuracy** ..."
6,local,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is preferred over naive retri...
7,local,What does the weighted multimodal score equati...,The **Weighted Multimodal Retrieval Score** is...
8,global,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal RAG (Retrie...
9,global,How did hybrid accuracy and latency change fro...,"Between January and June, **Hybrid Accuracy** ..."
10,global,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is considered superior to nai...
11,global,What does the weighted multimodal score equati...,The **weighted multimodal retrieval score** is...
12,hybrid,What is the main purpose of the multimodal RAG...,The main purpose of the multimodal Retrieval A...
13,hybrid,How did hybrid accuracy and latency change fro...,"Between January and June, significant changes ..."
14,hybrid,Why is hybrid retrieval better than naive retr...,Hybrid retrieval is considered superior to nai...
15,hybrid,What does the weighted multimodal score equati...,The **Weighted Multimodal Retrieval Score** is...

In [ ]:
print("\n[10/10] Running explicit multimodal queries...")
async def run_multimodal_queries():
   multimodal_cases = [
       {
           "name": "Table-aware query",
           "question": (
               "Using the supplied table, identify the month with the highest hybrid accuracy, "
               "the month with the lowest latency, and explain whether the trend supports the report conclusion."
           ),
           "multimodal_content": [
               {
                   "type": "table",
                   "table_data": table_md,
                   "table_caption": "Monthly performance table",
               }
           ],
       },
       {
           "name": "Equation-aware query",
           "question": (
               "Explain how this scoring equation should affect retrieval when the user's question needs "
               "textual, graph, and visual evidence at the same time."
           ),
           "multimodal_content": [
               {
                   "type": "equation",
                   "latex": r"Score(q,d)=\alpha Sim_{text}(q,d)+\beta Sim_{graph}(q,d)+\gamma Sim_{visual}(q,d)",
                   "equation_caption": "Weighted multimodal retrieval score",
               }
           ],
       },
       {
           "name": "Combined multimodal query",
           "question": (
               "Connect the table, equation, and document conclusion into one explanation of why a multimodal "
               "hybrid retriever is useful."
           ),
           "multimodal_content": [
               {
                   "type": "table",
                   "table_data": table_md,
                   "table_caption": "Monthly performance table",
               },
               {
                   "type": "equation",
                   "latex": r"Score(q,d)=\alpha Sim_{text}(q,d)+\beta Sim_{graph}(q,d)+\gamma Sim_{visual}(q,d)",
                   "equation_caption": "Weighted multimodal retrieval score",
               },
           ],
       },
   ]
   outputs = []
   for case in multimodal_cases:
       print("\n" + "=" * 80)
       print(case["name"])
       print("=" * 80)
       print("Question:", case["question"])
       try:
           answer = await rag.aquery_with_multimodal(
               case["question"],
               multimodal_content=case["multimodal_content"],
               mode="hybrid",
           )
       except Exception as e:
           answer = f"Multimodal query failed: {repr(e)}"
       print("\nAnswer:")
       print(answer)
       outputs.append(
           {
               "case": case["name"],
               "question": case["question"],
               "answer_preview": str(answer)[:900],
           }
       )
   return pd.DataFrame(outputs)
multimodal_results_df = await run_multimodal_queries()
print("\nMultimodal result preview:")
display(multimodal_results_df)
print("\nOptional full-parser path:")
print("RUN_FULL_DOCUMENT_PARSE is currently:", RUN_FULL_DOCUMENT_PARSE)
async def optional_full_document_parse():
   if not RUN_FULL_DOCUMENT_PARSE:
       print(
           "Skipping parser-based PDF ingestion. "
           "Set RUN_FULL_DOCUMENT_PARSE=True near the top to test MinerU/Docling/PaddleOCR parsing."
       )
       return
   print("Starting full document parsing.")
   await rag.process_document_complete(
       file_path=str(report_pdf_path),
       output_dir=str(OUTPUT_DIR),
       parse_method=PARSE_METHOD,
       parser=PARSER_FOR_FULL_PARSE,
       display_stats=True,
       doc_id="parser-processed-synthetic-report",
   )
   answer = await safe_aquery(
       "After full parsing, what figures, tables, and equations are present in the report?",
       mode="hybrid",
       vlm_enhanced=False,
   )
   print(answer)
await optional_full_document_parse()
print("\n" + "=" * 80)
print("Tutorial complete.")
print("=" * 80)
print(f"Assets directory: {ASSET_DIR}")
print(f"RAG storage directory: {WORKING_DIR}")
print(f"Output directory: {OUTPUT_DIR}")
print("\nGenerated files:")
for path in sorted(ASSET_DIR.glob("*")):
   print(" -", path)

INFO: Executing multimodal query: Using the supplied table, identify the month with the highest hybrid accuracy, the month with the lo...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/1 multimodal content: table

[10/10] Running explicit multimodal queries...

================================================================================
Table-aware query
================================================================================
Question: Using the supplied table, identify the month with the highest hybrid accuracy, the month with the lowest latency, and explain whether the trend supports the report conclusion.

INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 1894 characters
INFO: Executing VLM enhanced query: User query: Using the supplied table, identify the month with the highest hybrid accuracy, the month...
INFO:  == LLM cache == saving: hybrid:keywords:57e7eb98c9db0362c79b830e9350a72f
INFO: Query nodes: January, February, March, April, May, June, Query volume, Performance metrics (top_k:40, cosine:0.2)
INFO: Local query: 30 entites, 60 relations
INFO: Query edges: Hybrid accuracy, Average latency, Monthly performance analysis, Trend analysis (top_k:40, cosine:0.2)
INFO: Global query: 27 entites, 40 relations
INFO: Raw search results: 34 entities, 60 relations, 0 vector chunks
INFO: After truncation: 34 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 34 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E14/1 E15/2 E11/3 E6/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed
INFO: Executing multimodal query: Explain how this scoring equation should affect retrieval when the user's question needs textual, gr...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/1 multimodal content: equation

Answer:
Based on the supplied table, the analysis of the monthly performance metrics from January to June reveals the following key findings:

### Month with the Highest Hybrid Accuracy
The **highest hybrid accuracy** was recorded in **June**, with a value of **0.91**. This indicates that the system's responses were most accurate in this month.

### Month with the Lowest Latency
The **lowest average latency** occurred in **June**, at **730 milliseconds**. This signifies that during this month, the system was at its most efficient, processing queries the fastest.

### Trend Analysis
The trends observed in the table support the report's conclusions regarding the performance of the multimodal retrieval system:

1. **Positive Correlation Between Metrics**:
   - As hybrid accuracy improved from **0.71** in January to **0.91** in June, there was also a noticeable increase in query volume from **1200** to **4100**. This indicates that the system effectively handled a growing number of queries while enhancing its accuracy.
   - **Average latency decreased** consistently over the same period, indicating that not only was the accuracy improving, but the system also became faster in processing queries.

2. **Implications of Performance Improvements**:
   - The **increase in hybrid accuracy** supports the effectiveness of the hybrid retrieval method employed by the system, emphasized in the report. Higher accuracy rates correlate with improved user satisfaction and better system reliability.
   - The **decrease in latency** further illustrates the operational efficiency of the system, allowing for quicker responses during periods of increased usage.

### Conclusion
In summary, the trends in hybrid accuracy, query volume, and average latency all indicate a systematic improvement in the multimodal retrieval system's performance over the months analyzed. This supports the report's conclusion that the hybrid retrieval approach is beneficial and indicates enhanced capacity for addressing cross-modal questions.

### References
### References

- [1] synthetic_multimodal_rag_report.pdf

================================================================================
Equation-aware query
================================================================================
Question: Explain how this scoring equation should affect retrieval when the user's question needs textual, graph, and visual evidence at the same time.

INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 3351 characters
INFO: Executing VLM enhanced query: User query: Explain how this scoring equation should affect retrieval when the user's question needs...
INFO:  == LLM cache == saving: hybrid:keywords:e9334ca9d5fa1648d04ae0ee643b539b
INFO: Query nodes: Weighted multimodal retrieval score, Similarity measures, Textual content, Knowledge graphs, Visual content, Document relevance, Multimedia search systems, Recommendation systems (top_k:40, cosine:0.2)
INFO: Local query: 30 entites, 60 relations
INFO: Query edges: Scoring equation, Retrieval effectiveness, Multimodal retrieval, Information retrieval, User query (top_k:40, cosine:0.2)
INFO: Global query: 29 entites, 40 relations
INFO: Raw search results: 32 entities, 60 relations, 0 vector chunks
INFO: After truncation: 32 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 32 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E9/1 E9/2 E12/3 E12/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed
INFO: Executing multimodal query: Connect the table, equation, and document conclusion into one explanation of why a multimodal hybrid...
INFO: Query mode: hybrid
INFO: Starting multimodal query content processing...
INFO: Processing 1/2 multimodal content: table

Answer:
When a user’s question necessitates textual, graphical, and visual evidence at the same time, the **weighted multimodal retrieval score** plays a crucial role in optimizing the retrieval process. This scoring equation integrates multiple types of similarity measures, which facilitates a comprehensive assessment of document relevance based on diverse data types.

### Key Components of the Scoring Equation

1. **Final Score Calculation**:
   - The score \(Score(q, d)\) reflects how well document \(d\) addresses query \(q\).
   - It aggregates contributions from different similarity measures weighted by \(\alpha\), \(\beta\), and \(\gamma\):
     - \(Sim_{text}(q,d)\): Measures textual similarity (e.g., keyword relevance).
     - \(Sim_{graph}(q,d)\): Reflects similarity based on graph relationships or structural data.
     - \(Sim_{visual}(q,d)\): Assesses the relevance of visual content related to the query.

2. **Weighting Mechanism**:
   - Each similarity type is assigned a weight (α, β, γ) that controls its influence on the score. This flexibility allows the retrieval system to prioritize certain data forms depending on the context or specific user needs.

### Implications for Retrieval

1. **Holistic Search Experience**:
   - When queries demand information across multiple modalities, this scoring method ensures that documents are evaluated on all relevant dimensions, leading to results that holistically meet user needs.
   - For instance, a query asking for a report (text) with supporting graphs (visual) will benefit from documents that score highly across all similarity measures.

2. **Effective Ranking**:
   - The integration of varied types of similarity enables the retrieval system to rank documents more effectively based on how well they satisfy the query’s multifaceted requirements. This is particularly beneficial in multimedia search contexts or sophisticated recommendation systems.

3. **Personalized Retrieval**:
   - By adjusting the weights (\(\alpha\), \(\beta\), \(\gamma\),) depending on the user's context or preferences, the system can enhance personalization. For instance, if a user is more visually inclined, the weight assigned to visual similarity can be increased, enhancing the relevance of visual content in the results.

### Conclusion

The weighted multimodal retrieval score not only provides a means of quantifying relevance across diverse data types, but also enhances the overall user experience. By enabling a comprehensive evaluation that accounts for textual, graphical, and visual elements, this scoring equation is essential for modern information retrieval systems. Such systems can effectively address complex user queries that require an integrative approach to content, ultimately leading to improved relevance and user satisfaction.

### References

- [1] synthetic_multimodal_rag_report.pdf

================================================================================
Combined multimodal query
================================================================================
Question: Connect the table, equation, and document conclusion into one explanation of why a multimodal hybrid retriever is useful.

INFO: Processing 2/2 multimodal content: equation
INFO: Multimodal query content processing completed
INFO: Generated enhanced query length: 5176 characters
INFO: Executing VLM enhanced query: User query: Connect the table, equation, and document conclusion into one explanation of why a multi...
INFO:  == LLM cache == saving: hybrid:keywords:8f7f2f261d12d6befbdb8aae77a82f0d
INFO: Query nodes: Query Volume, Hybrid Accuracy, Average Latency, Weighted multimodal retrieval score, Textual similarity, Graph similarity, Visual similarity, Information retrieval, Multimedia databases (top_k:40, cosine:0.2)
INFO: Local query: 35 entites, 60 relations
INFO: Query edges: Multimodal hybrid retriever, Document retrieval, Data integration, Performance overview, Retrieval score (top_k:40, cosine:0.2)
INFO: Global query: 28 entites, 40 relations
INFO: Raw search results: 36 entities, 60 relations, 0 vector chunks
INFO: After truncation: 36 entities, 60 relations
INFO: Selecting 4 from 4 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 4 -> 4 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 36 entities, 60 relations, 4 chunks
INFO: Final chunks S+F/O: E9/1 E14/2 E11/3 E14/4
INFO: Found 1 image path matches in prompt
INFO: Processed 1 images for VLM
INFO: VLM enhanced query completed
INFO: Saved multimodal query result to cache: multimodal_query...
INFO: Multimodal query completed

Answer:
The integration of a multimodal hybrid retriever, as illustrated through the analysis of a performance table, a weighted multimodal retrieval score equation, and the conclusions drawn in the related document, demonstrates its significant utility in information retrieval systems.

### 1. Performance Table Insights

The performance table tracks the evolution of three critical metrics—from January to June: **Query Volume**, **Hybrid Accuracy**, and **Average Latency**. Here are the key observations:

- **Query Volume**: This metric shows a consistent increase, starting at **1200 in January** and reaching **4100 in June**. This growth indicates rising user engagement and the system's growing capability to handle more requests.

- **Hybrid Accuracy**: This metric, which measures the correctness of the results delivered by the system, improved from **0.71 to 0.91** over the same timeframe. Such enhancement suggests that the underlying algorithms and retrieval methods are becoming increasingly reliable at delivering relevant information.

- **Average Latency**: Notably, average response times decreased from **980 ms to 730 ms**. This improvement in latency alongside increasing query volume indicates that the system is becoming more efficient, demonstrating an effective optimization of resources.

The positive correlation between query volume and hybrid accuracy showcases how the system learns and adapts; as it processes more queries, its accuracy improves, reinforcing the effectiveness of the multimodal hybrid retriever in managing and responding to diverse inquiries.

### 2. Weighted Multimodal Retrieval Score Equation

The **weighted multimodal retrieval score** quantitatively assesses the relevance of documents concerning user queries, utilizing multiple modalities such as text, graph relationships, and visual content. The equation is structured as follows:

\[
\text{Score}(q, d) = \alpha \cdot \text{Sim}_{\text{text}}(q,d) + \beta \cdot \text{Sim}_{\text{graph}}(q,d) + \gamma \cdot \text{Sim}_{\text{visual}}(q,d)
\]

In this formula:
- **Weights (\(\alpha\), \(\beta\), and \(\gamma\))** allow for customization based on the specific context and relevance of each similarity type.
- It balances different types of information, ensuring a holistic view is applied when determining the score, thus enhancing the relevance of retrieved documents.

This flexible scoring mechanism allows the multimodal hybrid retriever to prioritize different data types based on the user's context, making it versatile across various information retrieval scenarios, such as multimedia databases and complex queries.

### 3. Document Conclusions

The related document emphasizes the effectiveness of hybrid retrieval systems in addressing **cross-modal questions**. Key findings include:

- **Hybrid Retrieval** is the preferred technique for processing complex queries that span multiple modalities, capitalizing on the advantages of rich, varied data.
- As the system processes more queries, improvements in hybrid accuracy and reductions in average latency were noted, highlighting how the implementation of hybrid methods contributes to refined search experiences.

### Conclusion

In essence, the synergy between the performance metrics showcased in the table, the robustness of the weighted multimodal retrieval equation, and the compelling conclusions from the document illustrates the value of a multimodal hybrid retriever. It enhances efficiency and accuracy, enabling retrieval systems to adapt critically to user demands while effectively managing diverse types of information.

### References

- [1] synthetic_multimodal_rag_report.pdf

Multimodal result preview:

,case,question,answer_preview
0,Table-aware query,"Using the supplied table, identify the month w...","Based on the supplied table, the analysis of t..."
1,Equation-aware query,Explain how this scoring equation should affec...,"When a user’s question necessitates textual, g..."
2,Combined multimodal query,"Connect the table, equation, and document conc...",The integration of a multimodal hybrid retriev...

Optional full-parser path:
RUN_FULL_DOCUMENT_PARSE is currently: False
Skipping parser-based PDF ingestion. Set RUN_FULL_DOCUMENT_PARSE=True near the top to test MinerU/Docling/PaddleOCR parsing.

================================================================================
Tutorial complete.
================================================================================
Assets directory: /content/raganything_advanced_tutorial/assets
RAG storage directory: /content/raganything_advanced_tutorial/rag_storage
Output directory: /content/raganything_advanced_tutorial/output

Generated files:
 - /content/raganything_advanced_tutorial/assets/content_list.json
 - /content/raganything_advanced_tutorial/assets/raganything_quality_trend.png
 - /content/raganything_advanced_tutorial/assets/synthetic_multimodal_rag_report.pdf